
@withSocialBar = true
@withAfterPostIntroduce = false
@withChat = false
@withDiscover = true
@withAutoSavedOnPaused = true
@withPostSuggestionToUser = false
@withNewLayoutMoment = true
@withMusicSharing = true
@withSectionMenu = true
@withSectionShare = true
@withPostTTS = false
@withWeChatSignatureServer = false
@withLocalBase64 = true
@withSuggestAlreadyRead = true
@withForcePopupSectionReview = false
@withSponserLinkAds = false
@isUSVersion = false
@withZhiFaCDN = false
@withServerImport = true
@withSlackReporter = false
@withSkypeWebReporter = true
@withShareStoryGroup = true
@withDirectDraftShow = true
@withMobileBackendUploading = false
@withStaticPosts = false
@withNewFilePath=true
@withLanguageSetting=false
@withImportToEdit=false
@signUpUserNameLength = 16
@withPostTitleMaxLength = 180      #byte
@withPostSubTitleMaxLength = 120   #byte
@withNeo4JInDynamicPostFriend = true
@withNeo4JInMoment = true
@withNeo4JInFollowPosts = true
@MQTT_TIME_DIFF = 0
# @withLoginTokenMax = 10
@CHECK_UPDATE = true # 强制更新和推荐更新启用标志
@withFromExample = false #故事贴从样例创建
@withPinImage = false #pin图
@withQRTips = true
@syncToNeo4jWithMqtt = false  #false->直接操作Neo4j true->mqttsync
@enableSimpleEditor = true # true 启用新编辑器 false 不启用
@withEnableHaveReadMsg = false #已读消息
@withEnableUniversalLink = true #深度链接唤醒App
@withSectionRateToOwner = true #点评消息更新到Feed里
@withPostGroupChat = true #点评、赞踩、转发贴子时产生故事群
@withShowGroupsUserMaxCount = 29
@withMutePushNotification = true #屏蔽群聊推送
@withFollowTopic = true #新注册用户首页进入关注页面
@CHAT_RENDER_TIME = 150
@isShowAllowComment = true